<h1>Numpy</h1>

In [2]:
import numpy as np

In [4]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
y = [1,2,3,4]
print(y )
print(type(y))

[1, 2, 3, 4]
<class 'list'>


<h2>Time difference between the numpy and List </h2>

In [12]:
%timeit [j**4 for j in range(1,9)]

3.16 µs ± 80 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%timeit np.arange(1,9)**4

1.71 µs ± 249 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Array 

In [7]:
import numpy as np
x=[1,2,3,4,5]
y=np.array(x)
print(y)
print(y.ndim)

[1 2 3 4 5]
1


In [6]:
l = []
for i in range(1,5):
    int_1 = int(input("Enter : "))
    l.append(int_1)
print(np.array(l))

Enter : 11
Enter : 12
Enter : 13
Enter : 14
[11 12 13 14]


In [8]:
ar2 = np.array([[1,2,3,4],[2,4,5,6]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [2 4 5 6]]
2


In [10]:
ar3 = np.array([[[1,2,3,4],[2,3,4,5],[3,4,5,6]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]]
3


In [12]:
arn = np.array([1,2,3,4] , ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros

In [16]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print(" ")
print(ar_zero1)

[0. 0. 0. 0.]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [21]:
ar_one = np.ones(4)
ar_one1 = np.ones((3,5))
print(ar_one)
print("")
print(ar_one1)

[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Empty

In [22]:
ar_em = np.empty(4)
# it takes the storage of the previous data that is store 
print(ar_em)

[1. 1. 1. 1.]


# Range

In [23]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

In [24]:
ar_dia = np.eye(3) # it create a 3x3 matrix
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
ar_dia = np.eye(3,5) # it create a 3x3 matrix
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace

In [28]:
ar_lin = np.linspace(0 , 20, num = 5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# Random 

In [2]:
import numpy as np

## Rand()

In [5]:
var  = np.random.rand(4)
print(var)

[0.05735889 0.71134008 0.53567815 0.52026641]


In [6]:
var1   = np.random.rand(2,5)
print(var1)

[[0.747796   0.72400388 0.92248695 0.37846907 0.73944986]
 [0.26691164 0.48126077 0.10421164 0.85347876 0.24981263]]


## randn()

In [8]:
var2  = np.random.randn(5)
print(var2)

[-0.55552657 -1.34645546 -0.11054983 -0.33781123 -0.35192658]


## randf()

In [11]:
var3 = np.random.ranf(4)
print(var3)

[0.69739747 0.76844085 0.18968068 0.23764349]


## Randint()

In [12]:
var4 = np.random.randint(5,20,6)
print(var4) 


[17 14 10  9 19 15]


In [14]:
var5 = np.random.randint(5,6,5)
print(var5)

[5 5 5 5 5]


# Data Type in Numpy

In [16]:
var6  = np.array([1,2,3,4,5,6,7,8,9])
print("Data Types : " , var6.dtype)

Data Types :  int32


In [17]:
var7 = np.array([0.2,4.5,6.4,6.5,6.4])
print("Data Types : " , var7.dtype)

Data Types :  float64


In [20]:
var8 = np.array(["Brijesh" , "Singh" ,"Sahasi"])
print("Data Types : " , var8.dtype)

Data Types :  <U7


In [21]:
var9= np.array(["Brijesh" , "Singh" ,"Sahasi",1,2,3,4])
print("Data Types : " , var9.dtype)

Data Types :  <U11


In [23]:
x = np.array([1,2,3,4],dtype= np.int8)
print("Data type : " , x.dtype)
print(x)

Data type :  int8
[1 2 3 4]


In [25]:
x1 = np.array([1,2,3,4],dtype= "f")
print("Data type : " , x1.dtype)
print(x1)

Data type :  float32
[1. 2. 3. 4.]


In [27]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
print("Data type : " , x2.dtype)
print("Data type : " , new.dtype)
print(x2)
print(new)

Data type :  int32
Data type :  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [28]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


#  Arithmetic Operation

In [2]:
import numpy as np

In [3]:
var  = np.array([1,2,3,4])
varadd = var+3
#np.add(var,3)
print(varadd)

[4 5 6 7]


In [5]:
var1  = np.array([1,2,3,4])
var2  = np.array([1,2,3,4])
varadd = var1+var2
print(varadd)

[2 4 6 8]


In [14]:
var1  = np.array([1,2,3,4])
var2  = np.array([1,2,3,4])
varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [ ]:
var  = np.array([1,2,3,4])
varadd = var-3
#np.subtract(var , 3)
print(varadd)

In [9]:
var  = np.array([1,2,3,4])
varadd = var*3
print(varadd)

[ 3  6  9 12]


In [10]:
var  = np.array([1,2,3,4])
varadd = var/3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [12]:
var  = np.array([1,2,3,4])
varadd = var%3
print(varadd)

[1 2 0 1]


In [17]:
var  = np.array([1,2,3,4])
varadd = np.reciprocal(var)
print(varadd)

[1 0 0 0]


# All Numpy arithmetic operation

 a+b          np.add(a,b)                                                                                                  
 a-b          np.subtract(a,b)                                                                                              
 a*b          np.multiply(a,b)                                                                                               
 a/b          np.divide(a,b)                                                                                                 
 a%b          np.mode(a,b)                                                                                                    
 a**b         np.power(a,b)                                                                                                   
 1/a          np.reciprocal(a)                                                                                                

# 2D array

In [16]:
var21  = np.array([[1,2,3,4],[1,2,3,4]])
var22  = np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()

varadd = np.add(var21,var22)
print(varadd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


# Arithmetic Function

np.min(x)                                                                                                                  
np.max(x)                                                                                                                   
np.argmin(x)                                                                                                                 
np.sqrt(x)                                                                                                                   
np.sin(x)                                                                                                                    
np.cos(x)                                                                                                                     
np.cumsum(x)                                                                                                                  

In [22]:
var3 = np.array([1,2,4,5,6,8,9,45])
print("min" , np.min(var3), "index" , np.argmin(var3))
print("max" , np.max(var3) , "index" , np.argmax(var3))
print("sqrt" , np.sqrt(var3))

min 1 index 0
max 45 index 7
sqrt [1.         1.41421356 2.         2.23606798 2.44948974 2.82842712
 3.         6.70820393]


In [21]:
var4 = np.array([[2,1,3],[9,5,4]])
print(np.min(var4 , axis = 0)) # axis 0 for the coloumn wise 1 for row wise min 
print(np.min(var4 , axis = 1)) # row wise min

[2 1 3]
[1 4]


In [24]:
var4 = np.array([1,2,3,4])
print(np.sin(var4))
print(np.cos(var4))
print(np.cumsum(var4))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1  3  6 10]


# Shape


In [3]:
import numpy as np
var5 = np.array([[1,2,3,4] , [1,2,3,4]])
print(var5)
print()
print(var5.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [9]:
var6 = np.array([1,2,3,4], ndmin=4)
print(var6)
print()
print(var6.shape)
print(var6.ndim)

[[[[1 2 3 4]]]]

(1, 1, 1, 4)
4


# Reshape


In [7]:
var7 = np.array([1,2,3,4,5,6])
print(var7)
print(var7.ndim)
print()
x = var7.reshape(3,2)
print()
print(x)
print(x.ndim)


[1 2 3 4 5 6]
1


[[1 2]
 [3 4]
 [5 6]]
2


In [14]:
var8 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var8)
print(var8.ndim)
print()
x1 = var8.reshape(2,3,2)
print()
print(x1)
print(x1.ndim)

one = x1.reshape(-1) # convert it into the one Dimension array 
print(one)
print(one.ndim)
 
two = x1.reshape(2,6)
print(two)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# Broadcasting

In [19]:
var9 = np.array([1,2,3])
print(var9.shape)
print(var9)
print()
var10 = np.array([[1],[2],[3]])
print(var10.shape)
print(var10)
print()
print(var9 + var10)

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [3]:
x = np.array([[1],[2]])
print(x.shape)
print()
y = np.array([[1,2,3] , [1,2,3]])

print(y.shape)
print()
print(x+y)

(2, 1)

(2, 3)

[[2 3 4]
 [3 4 5]]


# Indexing

In [5]:
x1 = np.array([1,2,3,4])
# indexing     0 ,1,2,3
# indexing     -4 ,-3,-2,-1
print(x1[3])
print(x1[-3])

4
2


In [9]:
x2 = np.array([[1,2,3],[4,5,6]])
print(x2[0][2])  # or 
print(x2[0,2])  #both are same

3
3


In [13]:
x3 = np.array([[[1,2],[3,4]]])
print(x3)
print(x3.ndim)
print()
print(x3[0,1,1])

[[[1 2]
  [3 4]]]
3

4


# Slicing

x[start : end] 

In [20]:
x4 = np.array([1,2,3,4,5,6,7])
print(x4)
print()
print("2 to 5 :" , x4[1:5])
print("2 to end :" , x4[2:])
print("start to 5" , x4[:5])

print("Stop :" , x4[1:5:2])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 to end : [3 4 5 6 7]
start to 5 [1 2 3 4 5]
Stop : [2 4]


In [23]:
x5 = np.array([[1,2,3,3,4,5],[6, 7,8,9,10,11],[11,12,13,14,15,16]])
print(x5)
print(x5.ndim)
print()
print("7 to 11" , x5[1 , 1:])

[[ 1  2  3  3  4  5]
 [ 6  7  8  9 10 11]
 [11 12 13 14 15 16]]
2

7 to 11 [ 7  8  9 10 11]


<center><h1>iteration in numpy</h1></center>

In [25]:
x6  = np.array([1,2,3,4,5,6,7,8])
print(x6)
print()
for i in x6:
    print(i)

[1 2 3 4 5 6 7 8]

1
2
3
4
5
6
7
8


In [28]:
x7 = np.array([[1,2,3,4],[1,2,3,4]])
print(x7)

print()

for i in x7:
    for j in i:
        print(j)

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [30]:
x8 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(x8)
print(x8.ndim)

for i in x8:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [1 2 3 4]]]
3
1
2
3
4
1
2
3
4


In [37]:
x8 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(x8)
print(x8.ndim)

for i in np.nditer(x8):
    print(i)

# change the data type
for i in np.nditer(x8 , flags=['buffered'], op_dtypes=['S']):
    print(i)

[[[1 2 3 4]
  [1 2 3 4]]]
3
1
2
3
4
1
2
3
4
b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [39]:
x8 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(x8)
print(x8.ndim)

for i,d in np.ndenumerate(x8):
    print(i,d)

[[[1 2 3 4]
  [1 2 3 4]]]
3
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


<center><h1 style="color:green">Copy vs view </h1></center>

In [45]:
var = np.array([1,2,3,4])

co = var.copy()  # copy the var variable to the co variable

var[1] = 40
print("var : " , var )
print("co  : " , co)

var :  [ 1 40  3  4]
co  :  [1 2 3 4]


In [46]:
x = np.array([1,2,3,4])

vi = x.view()
x[1] = 40
print("var : ", x)
print("view : ", vi)

var :  [ 1 40  3  4]
view :  [ 1 40  3  4]


<h1>copy</h1>
<ul>
    <li>the copy owns the data</li>
     <li>the copy of an array is a new array</li>
     <li>the change made in copy data does not reflect in the original array</li>
  </ul>
  
 <h1>View</h1>
<ul>
    <li>the view does not own the data</li>
     <li>A view of the original array</li>
     <li>any change made to the view will affect the  original array</li>
  </ul>

# Join Array

In [5]:
var = np.array([1,2,3,4])
var1 = np.array([9 ,8,7,6])
var2 = np.array([10,12])
ar = np.concatenate((var,var1,var2))
print(ar)

[ 1  2  3  4  9  8  7  6 10 12]


In [9]:
var3 = np.array([[1,2],[3,4]])
var4 = np.array([[9,8],[7,6]])
ar = np.concatenate((var3,var4),axis=1)  # second parameter is for axis 1 for row wise 0 for columns wise
print(ar)

[[1 2 9 8]
 [3 4 7 6]]


In [4]:
var_1 = np.array([1,2,3,4])
var_2= np.array([9 ,8,7,6])

a_new = np.stack((var_1 , var_2) , axis =0)
a_new1= np.stack((var_1 , var_2) , axis =1)
print()
print(a_new)
print()
print(a_new1)
print()
a_new2 = np.hstack((var_1,var_2))  # merge along horizontal
print(a_new2)
print()
a_new3 = np.vstack((var_1,var_2))  # merge along vertices
print(a_new3)
print()
a_new4 = np.dstack((var_1,var_2))  # merge along height
print(a_new4)


[[1 2 3 4]
 [9 8 7 6]]

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# Split Array

In [9]:
var = np.array([1,2,3,4,5,6])
print(var)

ar = np.array_split(var , 3)
print()
print(ar)
print(type(ar))

print(ar[0])



[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [13]:
var1 = np.array([[1,2],[3,4],[5,6]])
print(var1)
ar1 = np.array_split(var1,3)
print(ar1)
print()
ar2 = np.array_split(var1 , 3,axis = 1)
print(ar2)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


# Search


In [16]:
var = np.array([1,2,3,4,2,5,2,5,6,7])

x = np.where(var == 2)  # find the position of 2

y = np.where(var%2==0)

print(x)
print()
print(y)


(array([1, 4, 6], dtype=int64),)

(array([1, 3, 4, 6, 8], dtype=int64),)


In [25]:
var1 = np.array([1,2,3,4,6,7,8])

x1 = np.searchsorted( var1 , 5)  # where we place the 5 in var1 

x2 = np.searchsorted( var1 , 7, side="right") # place from the right side

x3 = np.searchsorted( var1 , [5,8,18], side = "right")

print(x1)

print(x2)

print(x3)

4
6
[4 7 7]


# sort

In [27]:
var3 = np.array([4,6,8,86,23,75,13,4,2,1])

print(np.sort(var3))

[ 1  2  4  4  6  8 13 23 75 86]


In [29]:
var4 = np.array([[4,6,8],[86,23,75],[13,4,2]])
print(np.sort(var4))

[[ 4  6  8]
 [23 75 86]
 [ 2  4 13]]


# Filter


In [2]:
import numpy as np
var5 = np.array(["a","s","d","f"])

f = [True , False,False , True]

new_a = var5[f]
print(new_a)

['a' 'f']


# Function in numpy

## Shuffle

In [12]:
var = np.array([1,2,3,4,5,6])
np.random.shuffle(var)
print(var)

[6 1 4 5 2 3]


## Unique

In [17]:
var1 = np.array([1,2,1,2,3,5,3,3,3,3,4,5,5,2])

x=np.unique(var1)
# return with the index
y = np.unique(var1, return_index=True)
# return with index and counting
z = np.unique(var1, return_index=True, return_counts=True)
print(x)
print(y)
print(z)


[1 2 3 4 5]
(array([1, 2, 3, 4, 5]), array([ 0,  1,  4, 10,  5], dtype=int64))
(array([1, 2, 3, 4, 5]), array([ 0,  1,  4, 10,  5], dtype=int64), array([2, 3, 5, 1, 3], dtype=int64))


## Resize

var2 = np.array([1,2,3,4,5,6])
t= np.resize(var2,(2,3))
print(t)

## Flatten 


In [25]:
var2 = np.array([1,2,3,4,5,6])
t= np.resize(var2,(2,3))
print("flatten : ",t.flatten(order="F"))  # convert 2D array to 1D array
print("revel : ", np.ravel(t,order="F"))

flatten :  [1 4 2 5 3 6]
revel :  [1 4 2 5 3 6]


# Insert 

In [35]:
var  = np.array([1,2,3,4])

print(var)
v = np.insert(var , 3 , 40)   #first is array name second is position and third is the value
v1 = np.insert(var, (2,4) , 60)  
print(v1)
print(v)
print(var)
v2 = np.insert(var, (2,4) , 6.5)  
print(v2)
v3 = np.append(var, 6.5)
print(v3)

[1 2 3 4]
[ 1  2 60  3  4 60]
[ 1  2  3 40  4]
[1 2 3 4]
[1 2 6 3 4 6]
[1.  2.  3.  4.  6.5]


In [42]:
var1 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var1,2,22, axis=0)
print(v1)
v1 = np.insert(var1,2,22, axis=1)
print(v1)
v1 = np.insert(var1,2,[22,23], axis=1)
print(v1)
v1 = np.insert(var1,2,[22,23,24], axis=0)
print(v1)

v2 = np.append(var1,[[3,3,3]], axis=0)
print(v2)


[[ 1  2  3]
 [ 1  2  3]
 [22 22 22]]
[[ 1  2 22  3]
 [ 1  2 22  3]]
[[ 1  2 22  3]
 [ 1  2 23  3]]
[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]
[[1 2 3]
 [1 2 3]
 [3 3 3]]


# Delete

In [3]:
var1 = np.array([1,2,3,4])
print(var1)
d = np.delete(var1,2) # 2 is the index value
print(d)

[1 2 3 4]
[1 2 4]


# Matrix 

In [9]:
var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var* var2)
print()
print(var.dot(var2))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


In [11]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))
print()
print(var1+var1)
print()
print(var1*var1)
print()

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[2 4 6]
 [2 4 6]]

[[1 4 9]
 [1 4 9]]



# Function in numpy 
 ### 1. Transpose 
 ### 2. swapaxes
 ### 3. Inverse
 ### 4 . Power
 ### 5. Determinate

In [20]:
var3 = np.matrix([[1,2,3],[4,5,6]])
print(var3)
print()
print(np.transpose(var3))
print()  # alternate for the  transpose 
print(var3.T)
# swapaxes 
print()
print(np.swapaxes(var3, 0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [22]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [25]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.linalg.inv(var2))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.matrix_power(var4,2))
print()

print(np.linalg.matrix_power(var4,0))
print()

print(np.linalg.matrix_power(var4,-2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [34]:
var5 = np.matrix([[1,2,4],[3,4,5],[5,6,7]])
print(var5)
print()
print(np.linalg.det(var5))

[[1 2 4]
 [3 4 5]
 [5 6 7]]

-1.9999999999999978
